services:
  ale-flix-db:
    image: postgres:16-alpine
    container_name: ale-flix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ale-flix
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ale-flix-network

  ale-flix-localstack:
    image: localstack/localstack:latest
    container_name: ale-flix-localstack
    environment:
      - SERVICES=lambda,s3,cloudwatch,logs,apigateway,dynamodb,sqs
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    ports:
      - '4566:4566'
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack-data:/tmp/localstack-s3-storage
    networks:
      - ale-flix-network

  ale-flix-web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: ale-flix-web
    ports:
      - '8081:3000'
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    env_file:
      - ./apps/web/.env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nginx-cors-proxy:80/v1/traces
    networks:
      - ale-flix-network
    command: yarn dev
    depends_on:
      - ale-flix-db
      - nginx-cors-proxy

  ale-flix-api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: ale-flix-api
    ports:
      - '4000:4000'
    volumes:
      - ./apps/api:/app
    depends_on:
      - ale-flix-db
    networks:
      - ale-flix-network
    # command: tail -f /dev/null

  ale-flix-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ale-flix-jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # Jaeger UI
      - 4317:4317
      # - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - ale-flix-network

  ale-flix-video-transcoder:
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/video-transcoder/Dockerfile
    # command: yarn start
    # command: tail -f /dev/null
    container_name: ale-flix-video-transcoder
    volumes:
      - ./apps/video-transcoder:/app
      # - /app/node_modules
    env_file:
      - ./apps/video-transcoder/.env
    depends_on:
      - init-localstack-setup
      - ale-flix-db
    networks:
      - ale-flix-network

  init-localstack-setup:
    image: python:3.11-alpine
    user: root
    container_name: ale-flix-init-localstack-setup
    entrypoint: >
      /bin/sh -c "
        apk add --no-cache curl bash py3-pip &&
        pip install awscli awscli-local &&
        /project/localstack-setup.sh
      "
    volumes:
      - ./localstack-setup.sh:/project/localstack-setup.sh
    depends_on:
      - ale-flix-localstack
    networks:
      - ale-flix-network

  ale-flix-redis:
    image: redis:7-alpine
    container_name: ale-flix-redis
    ports:
      - '6379:6379'
    networks:
      - ale-flix-network

  nginx-cors-proxy:
    image: nginx:alpine
    container_name: ale-flix-nginx-cors
    ports:
      - '8082:80'
    volumes:
      - ./nginx-cors.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ale-flix-network
    depends_on:
      - ale-flix-jaeger

networks:
  ale-flix-network:
    driver: bridge

volumes:
  postgres_data:
